# Generated by Django 3.1.2 on 2020-10-19 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nickname', models.CharField(max_length=255, verbose_name='Кличка')),
                ('gender', models.CharField(max_length=255, verbose_name='Пол')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('woolCover', models.CharField(max_length=255, verbose_name='Шерстяной покров')),
                ('woolColor', models.CharField(max_length=255, verbose_name='Цвет шерсти')),
                ('breed', models.CharField(max_length=255, verbose_name='Порода')),
                ('eyesColor', models.CharField(max_length=255, verbose_name='Цвет глаз')),
                ('toilet', models.BooleanField(verbose_name='Приученность к туалету')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('body', models.CharField(max_length=255, verbose_name='Телосложение')),
                ('advDescriptions', models.TextField(null=True, verbose_name='Дополнительное описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('typeName', models.CharField(max_length=255, verbose_name='Вид животного')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalProducts', models.PositiveIntegerField(default=0, verbose_name='Количество продуктов')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Конечная цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('midName', models.CharField(max_length=255, verbose_name='Отчество')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phoneNumber', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='VeteranaryClinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicNumber', models.IntegerField(verbose_name='Номер ветлечебницы')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phoneNumber', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('midName', models.CharField(max_length=255, verbose_name='Отчество')),
                ('dateOfReg', models.DateField(verbose_name='Дата введения в учёт')),
                ('lastVisit', models.DateField(verbose_name='Дата последнего посещения')),
                ('veteranaryClinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.veteranaryclinic', verbose_name='Ветлечебница')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phoneNumber', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CartElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.animal', verbose_name='Животное')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_elem', to='MainApp.cart', verbose_name='Корзина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.customer', verbose_name='Покупатель')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cartElements',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='MainApp.CartElem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animalsType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.animalstype', verbose_name='Вид животного'),
        ),
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.owner', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='animal',
            name='veterenaryClinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.veteranaryclinic', verbose_name='Ветлечебница'),
        ),
        migrations.AddField(
            model_name='animal',
            name='veterinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.veterinar', verbose_name='Ветеринар'),
        ),
    ]
