# Generated by Django 3.1.2 on 2020-10-19 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20201019_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.owner', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='veterenaryClinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.veteranaryclinic', verbose_name='Ветлечебница'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='veterinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.veterinar', verbose_name='Ветеринар'),
        ),
    ]
