# Generated by Django 3.1.2 on 2020-11-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20201019_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalstype',
            name='typeImage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
