# Generated by Django 3.1.2 on 2020-11-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_animalstype_typeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalstype',
            name='typeImage',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
