# Generated by Django 3.1.2 on 2020-11-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20201106_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(max_length=255, verbose_name='Возраст'),
        ),
    ]
