# Generated by Django 3.1.2 on 2020-11-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20201113_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foodType',
            field=models.CharField(default='Ooo', max_length=255, verbose_name='Тип питания'),
        ),
    ]
