# Generated by Django 3.1.2 on 2020-11-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_animal_shortdescriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='shortDescriptions',
            field=models.TextField(blank=True, default='asdf', null=True, verbose_name='Краткое описание'),
        ),
    ]
