# Generated by Django 3.1.2 on 2020-11-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_auto_20201113_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.animal', verbose_name='Животное')),
            ],
        ),
    ]
