# Generated by Django 3.1.2 on 2020-11-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_auto_20201116_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение на главном экране'),
        ),
    ]
