# Generated by Django 3.1.2 on 2020-12-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_animal_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='available',
            field=models.BooleanField(default=True, max_length=255, verbose_name='Доступен для покупки'),
        ),
    ]
