# Generated by Django 3.1.2 on 2020-12-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_auto_20201214_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veteranaryclinic',
            name='clinicNumber',
            field=models.CharField(max_length=255, verbose_name='Название ветлечебницы'),
        ),
    ]
