# Generated by Django 3.1.2 on 2021-06-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0019_auto_20210602_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='petproduct',
            name='available',
            field=models.BooleanField(default=True, max_length=255, verbose_name='Доступен для покупки'),
        ),
    ]
