# Generated by Django 3.1.2 on 2021-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_petproduct_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='petproduct',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='animals',
            field=models.ManyToManyField(to='MainApp.Animal'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='MainApp.PetProduct'),
        ),
    ]
