# Generated by Django 3.1.2 on 2021-06-03 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_auto_20210602_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='petproduct',
            name='count',
            field=models.CharField(default=1, max_length=255, verbose_name='Возраст'),
        ),
        migrations.CreateModel(
            name='CartPetProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCount', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.cart', verbose_name='Корзина')),
                ('petProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.petproduct', verbose_name='Зоотовары')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='MainApp.CartPetProduct', to='MainApp.PetProduct'),
        ),
    ]
